# Generated by Django 2.0.1 on 2018-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateTaken', models.DateField()),
                ('user', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('uID', models.CharField(max_length=15)),
            ],
        ),
    ]
