# Generated by Django 2.0.1 on 2018-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20180112_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(help_text='Enter a caption for the photo', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dateTaken',
            field=models.DateTimeField(),
        ),
    ]
