# Generated by Django 2.0.1 on 2018-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20180112_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='dateTaken',
            field=models.DateTimeField(verbose_name='Date taken'),
        ),
    ]
