# Generated by Django 2.0.1 on 2018-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180112_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uID',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
    ]
