# Generated by Django 2.0.1 on 2018-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20180114_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='dateTaken',
            field=models.DateField(verbose_name='Date taken'),
        ),
    ]
